/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedEmailTasksRouteImport } from './routes/_authenticated/email-tasks'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedOnlineUsersRouteImport } from './routes/_authenticated/online-users'
import { Route as AuthenticatedOperationLogsRouteImport } from './routes/_authenticated/operation-logs'
import { Route as AuthenticatedPersonalSettingsRouteImport } from './routes/_authenticated/personal-settings'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedRotaRouteImport } from './routes/_authenticated/rota'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedRotaIndexRouteImport } from './routes/_authenticated/rota/index'
import { Route as AuthenticatedRotaAttendanceRouteImport } from './routes/_authenticated/rota/attendance'
import { Route as AuthenticatedRotaAvailabilityRouteImport } from './routes/_authenticated/rota/availability'
import { Route as AuthenticatedRotaLeavesRouteImport } from './routes/_authenticated/rota/leaves'
import { Route as AuthenticatedRotaPositionsRouteImport } from './routes/_authenticated/rota/positions'
import { Route as AuthenticatedRotaPublicationsRouteImport } from './routes/_authenticated/rota/publications'
import { Route as AuthenticatedRotaRequestsRouteImport } from './routes/_authenticated/rota/requests'
import { Route as AuthenticatedRotaRosterRouteImport } from './routes/_authenticated/rota/roster'
import { Route as AuthenticatedRotaTemplatesRouteImport } from './routes/_authenticated/rota/templates'
import { Route as AuthenticatedRotaLeavesIndexRouteImport } from './routes/_authenticated/rota/leaves/index'
import { Route as AuthenticatedRotaLeavesLeaveIdRouteImport } from './routes/_authenticated/rota/leaves/$leaveId'
import { Route as AuthenticatedRotaLeavesNewRouteImport } from './routes/_authenticated/rota/leaves/new'
import { Route as AuthenticatedRotaPublicationsIndexRouteImport } from './routes/_authenticated/rota/publications/index'
import { Route as AuthenticatedRotaPublicationsPublicationIdRouteImport } from './routes/_authenticated/rota/publications/$publicationId'
import { Route as AuthenticatedRotaTemplatesIndexRouteImport } from './routes/_authenticated/rota/templates/index'
import { Route as AuthenticatedRotaTemplatesTemplateIdRouteImport } from './routes/_authenticated/rota/templates/$templateId'
import { Route as AuthenticatedRotaPublicationsPublicationIdIndexRouteImport } from './routes/_authenticated/rota/publications/$publicationId/index'
import { Route as AuthenticatedRotaPublicationsPublicationIdAssignmentsRouteImport } from './routes/_authenticated/rota/publications/$publicationId/assignments'
import { Route as AuthenticatedRotaPublicationsPublicationIdAttendanceRouteImport } from './routes/_authenticated/rota/publications/$publicationId/attendance'
import { Route as AuthenticatedRotaPublicationsPublicationIdAvailabilityRouteImport } from './routes/_authenticated/rota/publications/$publicationId/availability'
import { Route as AuthenticatedRotaPublicationsPublicationIdShiftChangesRouteImport } from './routes/_authenticated/rota/publications/$publicationId/shift-changes'
import { Route as AuthenticatedRotaPublicationsPublicationIdAvailabilityIndexRouteImport } from './routes/_authenticated/rota/publications/$publicationId/availability/index'
import { Route as AuthenticatedRotaPublicationsPublicationIdAvailabilityUserIdRouteImport } from './routes/_authenticated/rota/publications/$publicationId/availability/$userId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailTasksRoute = AuthenticatedEmailTasksRouteImport.update({
  id: '/email-tasks',
  path: '/email-tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnlineUsersRoute =
  AuthenticatedOnlineUsersRouteImport.update({
    id: '/online-users',
    path: '/online-users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationLogsRoute =
  AuthenticatedOperationLogsRouteImport.update({
    id: '/operation-logs',
    path: '/operation-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonalSettingsRoute =
  AuthenticatedPersonalSettingsRouteImport.update({
    id: '/personal-settings',
    path: '/personal-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRotaRoute = AuthenticatedRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRotaIndexRoute = AuthenticatedRotaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRotaRoute,
} as any)
const AuthenticatedRotaAttendanceRoute =
  AuthenticatedRotaAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedRotaRoute,
  } as any)
const AuthenticatedRotaAvailabilityRoute =
  AuthenticatedRotaAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRotaRoute,
  } as any)
const AuthenticatedRotaLeavesRoute = AuthenticatedRotaLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedRotaRoute,
} as any)
const AuthenticatedRotaPositionsRoute =
  AuthenticatedRotaPositionsRouteImport.update({
    id: '/positions',
    path: '/positions',
    getParentRoute: () => AuthenticatedRotaRoute,
  } as any)
const AuthenticatedRotaPublicationsRoute =
  AuthenticatedRotaPublicationsRouteImport.update({
    id: '/publications',
    path: '/publications',
    getParentRoute: () => AuthenticatedRotaRoute,
  } as any)
const AuthenticatedRotaRequestsRoute =
  AuthenticatedRotaRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedRotaRoute,
  } as any)
const AuthenticatedRotaRosterRoute = AuthenticatedRotaRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRotaRoute,
} as any)
const AuthenticatedRotaTemplatesRoute =
  AuthenticatedRotaTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedRotaRoute,
  } as any)
const AuthenticatedRotaLeavesIndexRoute =
  AuthenticatedRotaLeavesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRotaLeavesRoute,
  } as any)
const AuthenticatedRotaLeavesLeaveIdRoute =
  AuthenticatedRotaLeavesLeaveIdRouteImport.update({
    id: '/$leaveId',
    path: '/$leaveId',
    getParentRoute: () => AuthenticatedRotaLeavesRoute,
  } as any)
const AuthenticatedRotaLeavesNewRoute =
  AuthenticatedRotaLeavesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedRotaLeavesRoute,
  } as any)
const AuthenticatedRotaPublicationsIndexRoute =
  AuthenticatedRotaPublicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRotaPublicationsRoute,
  } as any)
const AuthenticatedRotaPublicationsPublicationIdRoute =
  AuthenticatedRotaPublicationsPublicationIdRouteImport.update({
    id: '/$publicationId',
    path: '/$publicationId',
    getParentRoute: () => AuthenticatedRotaPublicationsRoute,
  } as any)
const AuthenticatedRotaTemplatesIndexRoute =
  AuthenticatedRotaTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRotaTemplatesRoute,
  } as any)
const AuthenticatedRotaTemplatesTemplateIdRoute =
  AuthenticatedRotaTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AuthenticatedRotaTemplatesRoute,
  } as any)
const AuthenticatedRotaPublicationsPublicationIdIndexRoute =
  AuthenticatedRotaPublicationsPublicationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRotaPublicationsPublicationIdRoute,
  } as any)
const AuthenticatedRotaPublicationsPublicationIdAssignmentsRoute =
  AuthenticatedRotaPublicationsPublicationIdAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRotaPublicationsPublicationIdRoute,
  } as any)
const AuthenticatedRotaPublicationsPublicationIdAttendanceRoute =
  AuthenticatedRotaPublicationsPublicationIdAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedRotaPublicationsPublicationIdRoute,
  } as any)
const AuthenticatedRotaPublicationsPublicationIdAvailabilityRoute =
  AuthenticatedRotaPublicationsPublicationIdAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRotaPublicationsPublicationIdRoute,
  } as any)
const AuthenticatedRotaPublicationsPublicationIdShiftChangesRoute =
  AuthenticatedRotaPublicationsPublicationIdShiftChangesRouteImport.update({
    id: '/shift-changes',
    path: '/shift-changes',
    getParentRoute: () => AuthenticatedRotaPublicationsPublicationIdRoute,
  } as any)
const AuthenticatedRotaPublicationsPublicationIdAvailabilityIndexRoute =
  AuthenticatedRotaPublicationsPublicationIdAvailabilityIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedRotaPublicationsPublicationIdAvailabilityRoute,
    } as any,
  )
const AuthenticatedRotaPublicationsPublicationIdAvailabilityUserIdRoute =
  AuthenticatedRotaPublicationsPublicationIdAvailabilityUserIdRouteImport.update(
    {
      id: '/$userId',
      path: '/$userId',
      getParentRoute: () =>
        AuthenticatedRotaPublicationsPublicationIdAvailabilityRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/email-tasks': typeof AuthenticatedEmailTasksRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/online-users': typeof AuthenticatedOnlineUsersRoute
  '/operation-logs': typeof AuthenticatedOperationLogsRoute
  '/personal-settings': typeof AuthenticatedPersonalSettingsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/rota': typeof AuthenticatedRotaRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/rota/attendance': typeof AuthenticatedRotaAttendanceRoute
  '/rota/availability': typeof AuthenticatedRotaAvailabilityRoute
  '/rota/leaves': typeof AuthenticatedRotaLeavesRouteWithChildren
  '/rota/positions': typeof AuthenticatedRotaPositionsRoute
  '/rota/publications': typeof AuthenticatedRotaPublicationsRouteWithChildren
  '/rota/requests': typeof AuthenticatedRotaRequestsRoute
  '/rota/roster': typeof AuthenticatedRotaRosterRoute
  '/rota/templates': typeof AuthenticatedRotaTemplatesRouteWithChildren
  '/rota/': typeof AuthenticatedRotaIndexRoute
  '/rota/leaves/$leaveId': typeof AuthenticatedRotaLeavesLeaveIdRoute
  '/rota/leaves/new': typeof AuthenticatedRotaLeavesNewRoute
  '/rota/publications/$publicationId': typeof AuthenticatedRotaPublicationsPublicationIdRouteWithChildren
  '/rota/templates/$templateId': typeof AuthenticatedRotaTemplatesTemplateIdRoute
  '/rota/leaves/': typeof AuthenticatedRotaLeavesIndexRoute
  '/rota/publications/': typeof AuthenticatedRotaPublicationsIndexRoute
  '/rota/templates/': typeof AuthenticatedRotaTemplatesIndexRoute
  '/rota/publications/$publicationId/assignments': typeof AuthenticatedRotaPublicationsPublicationIdAssignmentsRoute
  '/rota/publications/$publicationId/attendance': typeof AuthenticatedRotaPublicationsPublicationIdAttendanceRoute
  '/rota/publications/$publicationId/availability': typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityRouteWithChildren
  '/rota/publications/$publicationId/shift-changes': typeof AuthenticatedRotaPublicationsPublicationIdShiftChangesRoute
  '/rota/publications/$publicationId/': typeof AuthenticatedRotaPublicationsPublicationIdIndexRoute
  '/rota/publications/$publicationId/availability/$userId': typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityUserIdRoute
  '/rota/publications/$publicationId/availability/': typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/email-tasks': typeof AuthenticatedEmailTasksRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/online-users': typeof AuthenticatedOnlineUsersRoute
  '/operation-logs': typeof AuthenticatedOperationLogsRoute
  '/personal-settings': typeof AuthenticatedPersonalSettingsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/rota/attendance': typeof AuthenticatedRotaAttendanceRoute
  '/rota/availability': typeof AuthenticatedRotaAvailabilityRoute
  '/rota/positions': typeof AuthenticatedRotaPositionsRoute
  '/rota/requests': typeof AuthenticatedRotaRequestsRoute
  '/rota/roster': typeof AuthenticatedRotaRosterRoute
  '/rota': typeof AuthenticatedRotaIndexRoute
  '/rota/leaves/$leaveId': typeof AuthenticatedRotaLeavesLeaveIdRoute
  '/rota/leaves/new': typeof AuthenticatedRotaLeavesNewRoute
  '/rota/templates/$templateId': typeof AuthenticatedRotaTemplatesTemplateIdRoute
  '/rota/leaves': typeof AuthenticatedRotaLeavesIndexRoute
  '/rota/publications': typeof AuthenticatedRotaPublicationsIndexRoute
  '/rota/templates': typeof AuthenticatedRotaTemplatesIndexRoute
  '/rota/publications/$publicationId/assignments': typeof AuthenticatedRotaPublicationsPublicationIdAssignmentsRoute
  '/rota/publications/$publicationId/attendance': typeof AuthenticatedRotaPublicationsPublicationIdAttendanceRoute
  '/rota/publications/$publicationId/shift-changes': typeof AuthenticatedRotaPublicationsPublicationIdShiftChangesRoute
  '/rota/publications/$publicationId': typeof AuthenticatedRotaPublicationsPublicationIdIndexRoute
  '/rota/publications/$publicationId/availability/$userId': typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityUserIdRoute
  '/rota/publications/$publicationId/availability': typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/_authenticated/email-tasks': typeof AuthenticatedEmailTasksRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/online-users': typeof AuthenticatedOnlineUsersRoute
  '/_authenticated/operation-logs': typeof AuthenticatedOperationLogsRoute
  '/_authenticated/personal-settings': typeof AuthenticatedPersonalSettingsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/rota': typeof AuthenticatedRotaRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/rota/attendance': typeof AuthenticatedRotaAttendanceRoute
  '/_authenticated/rota/availability': typeof AuthenticatedRotaAvailabilityRoute
  '/_authenticated/rota/leaves': typeof AuthenticatedRotaLeavesRouteWithChildren
  '/_authenticated/rota/positions': typeof AuthenticatedRotaPositionsRoute
  '/_authenticated/rota/publications': typeof AuthenticatedRotaPublicationsRouteWithChildren
  '/_authenticated/rota/requests': typeof AuthenticatedRotaRequestsRoute
  '/_authenticated/rota/roster': typeof AuthenticatedRotaRosterRoute
  '/_authenticated/rota/templates': typeof AuthenticatedRotaTemplatesRouteWithChildren
  '/_authenticated/rota/': typeof AuthenticatedRotaIndexRoute
  '/_authenticated/rota/leaves/$leaveId': typeof AuthenticatedRotaLeavesLeaveIdRoute
  '/_authenticated/rota/leaves/new': typeof AuthenticatedRotaLeavesNewRoute
  '/_authenticated/rota/publications/$publicationId': typeof AuthenticatedRotaPublicationsPublicationIdRouteWithChildren
  '/_authenticated/rota/templates/$templateId': typeof AuthenticatedRotaTemplatesTemplateIdRoute
  '/_authenticated/rota/leaves/': typeof AuthenticatedRotaLeavesIndexRoute
  '/_authenticated/rota/publications/': typeof AuthenticatedRotaPublicationsIndexRoute
  '/_authenticated/rota/templates/': typeof AuthenticatedRotaTemplatesIndexRoute
  '/_authenticated/rota/publications/$publicationId/assignments': typeof AuthenticatedRotaPublicationsPublicationIdAssignmentsRoute
  '/_authenticated/rota/publications/$publicationId/attendance': typeof AuthenticatedRotaPublicationsPublicationIdAttendanceRoute
  '/_authenticated/rota/publications/$publicationId/availability': typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityRouteWithChildren
  '/_authenticated/rota/publications/$publicationId/shift-changes': typeof AuthenticatedRotaPublicationsPublicationIdShiftChangesRoute
  '/_authenticated/rota/publications/$publicationId/': typeof AuthenticatedRotaPublicationsPublicationIdIndexRoute
  '/_authenticated/rota/publications/$publicationId/availability/$userId': typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityUserIdRoute
  '/_authenticated/rota/publications/$publicationId/availability/': typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/email-tasks'
    | '/invitations'
    | '/online-users'
    | '/operation-logs'
    | '/personal-settings'
    | '/roles'
    | '/rota'
    | '/settings'
    | '/users'
    | '/rota/attendance'
    | '/rota/availability'
    | '/rota/leaves'
    | '/rota/positions'
    | '/rota/publications'
    | '/rota/requests'
    | '/rota/roster'
    | '/rota/templates'
    | '/rota/'
    | '/rota/leaves/$leaveId'
    | '/rota/leaves/new'
    | '/rota/publications/$publicationId'
    | '/rota/templates/$templateId'
    | '/rota/leaves/'
    | '/rota/publications/'
    | '/rota/templates/'
    | '/rota/publications/$publicationId/assignments'
    | '/rota/publications/$publicationId/attendance'
    | '/rota/publications/$publicationId/availability'
    | '/rota/publications/$publicationId/shift-changes'
    | '/rota/publications/$publicationId/'
    | '/rota/publications/$publicationId/availability/$userId'
    | '/rota/publications/$publicationId/availability/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/email-tasks'
    | '/invitations'
    | '/online-users'
    | '/operation-logs'
    | '/personal-settings'
    | '/roles'
    | '/settings'
    | '/users'
    | '/'
    | '/rota/attendance'
    | '/rota/availability'
    | '/rota/positions'
    | '/rota/requests'
    | '/rota/roster'
    | '/rota'
    | '/rota/leaves/$leaveId'
    | '/rota/leaves/new'
    | '/rota/templates/$templateId'
    | '/rota/leaves'
    | '/rota/publications'
    | '/rota/templates'
    | '/rota/publications/$publicationId/assignments'
    | '/rota/publications/$publicationId/attendance'
    | '/rota/publications/$publicationId/shift-changes'
    | '/rota/publications/$publicationId'
    | '/rota/publications/$publicationId/availability/$userId'
    | '/rota/publications/$publicationId/availability'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/_authenticated/email-tasks'
    | '/_authenticated/invitations'
    | '/_authenticated/online-users'
    | '/_authenticated/operation-logs'
    | '/_authenticated/personal-settings'
    | '/_authenticated/roles'
    | '/_authenticated/rota'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/rota/attendance'
    | '/_authenticated/rota/availability'
    | '/_authenticated/rota/leaves'
    | '/_authenticated/rota/positions'
    | '/_authenticated/rota/publications'
    | '/_authenticated/rota/requests'
    | '/_authenticated/rota/roster'
    | '/_authenticated/rota/templates'
    | '/_authenticated/rota/'
    | '/_authenticated/rota/leaves/$leaveId'
    | '/_authenticated/rota/leaves/new'
    | '/_authenticated/rota/publications/$publicationId'
    | '/_authenticated/rota/templates/$templateId'
    | '/_authenticated/rota/leaves/'
    | '/_authenticated/rota/publications/'
    | '/_authenticated/rota/templates/'
    | '/_authenticated/rota/publications/$publicationId/assignments'
    | '/_authenticated/rota/publications/$publicationId/attendance'
    | '/_authenticated/rota/publications/$publicationId/availability'
    | '/_authenticated/rota/publications/$publicationId/shift-changes'
    | '/_authenticated/rota/publications/$publicationId/'
    | '/_authenticated/rota/publications/$publicationId/availability/$userId'
    | '/_authenticated/rota/publications/$publicationId/availability/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-tasks': {
      id: '/_authenticated/email-tasks'
      path: '/email-tasks'
      fullPath: '/email-tasks'
      preLoaderRoute: typeof AuthenticatedEmailTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/online-users': {
      id: '/_authenticated/online-users'
      path: '/online-users'
      fullPath: '/online-users'
      preLoaderRoute: typeof AuthenticatedOnlineUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operation-logs': {
      id: '/_authenticated/operation-logs'
      path: '/operation-logs'
      fullPath: '/operation-logs'
      preLoaderRoute: typeof AuthenticatedOperationLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal-settings': {
      id: '/_authenticated/personal-settings'
      path: '/personal-settings'
      fullPath: '/personal-settings'
      preLoaderRoute: typeof AuthenticatedPersonalSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rota': {
      id: '/_authenticated/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof AuthenticatedRotaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rota/': {
      id: '/_authenticated/rota/'
      path: '/'
      fullPath: '/rota/'
      preLoaderRoute: typeof AuthenticatedRotaIndexRouteImport
      parentRoute: typeof AuthenticatedRotaRoute
    }
    '/_authenticated/rota/attendance': {
      id: '/_authenticated/rota/attendance'
      path: '/attendance'
      fullPath: '/rota/attendance'
      preLoaderRoute: typeof AuthenticatedRotaAttendanceRouteImport
      parentRoute: typeof AuthenticatedRotaRoute
    }
    '/_authenticated/rota/availability': {
      id: '/_authenticated/rota/availability'
      path: '/availability'
      fullPath: '/rota/availability'
      preLoaderRoute: typeof AuthenticatedRotaAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRotaRoute
    }
    '/_authenticated/rota/leaves': {
      id: '/_authenticated/rota/leaves'
      path: '/leaves'
      fullPath: '/rota/leaves'
      preLoaderRoute: typeof AuthenticatedRotaLeavesRouteImport
      parentRoute: typeof AuthenticatedRotaRoute
    }
    '/_authenticated/rota/positions': {
      id: '/_authenticated/rota/positions'
      path: '/positions'
      fullPath: '/rota/positions'
      preLoaderRoute: typeof AuthenticatedRotaPositionsRouteImport
      parentRoute: typeof AuthenticatedRotaRoute
    }
    '/_authenticated/rota/publications': {
      id: '/_authenticated/rota/publications'
      path: '/publications'
      fullPath: '/rota/publications'
      preLoaderRoute: typeof AuthenticatedRotaPublicationsRouteImport
      parentRoute: typeof AuthenticatedRotaRoute
    }
    '/_authenticated/rota/requests': {
      id: '/_authenticated/rota/requests'
      path: '/requests'
      fullPath: '/rota/requests'
      preLoaderRoute: typeof AuthenticatedRotaRequestsRouteImport
      parentRoute: typeof AuthenticatedRotaRoute
    }
    '/_authenticated/rota/roster': {
      id: '/_authenticated/rota/roster'
      path: '/roster'
      fullPath: '/rota/roster'
      preLoaderRoute: typeof AuthenticatedRotaRosterRouteImport
      parentRoute: typeof AuthenticatedRotaRoute
    }
    '/_authenticated/rota/templates': {
      id: '/_authenticated/rota/templates'
      path: '/templates'
      fullPath: '/rota/templates'
      preLoaderRoute: typeof AuthenticatedRotaTemplatesRouteImport
      parentRoute: typeof AuthenticatedRotaRoute
    }
    '/_authenticated/rota/leaves/': {
      id: '/_authenticated/rota/leaves/'
      path: '/'
      fullPath: '/rota/leaves/'
      preLoaderRoute: typeof AuthenticatedRotaLeavesIndexRouteImport
      parentRoute: typeof AuthenticatedRotaLeavesRoute
    }
    '/_authenticated/rota/leaves/$leaveId': {
      id: '/_authenticated/rota/leaves/$leaveId'
      path: '/$leaveId'
      fullPath: '/rota/leaves/$leaveId'
      preLoaderRoute: typeof AuthenticatedRotaLeavesLeaveIdRouteImport
      parentRoute: typeof AuthenticatedRotaLeavesRoute
    }
    '/_authenticated/rota/leaves/new': {
      id: '/_authenticated/rota/leaves/new'
      path: '/new'
      fullPath: '/rota/leaves/new'
      preLoaderRoute: typeof AuthenticatedRotaLeavesNewRouteImport
      parentRoute: typeof AuthenticatedRotaLeavesRoute
    }
    '/_authenticated/rota/publications/': {
      id: '/_authenticated/rota/publications/'
      path: '/'
      fullPath: '/rota/publications/'
      preLoaderRoute: typeof AuthenticatedRotaPublicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRotaPublicationsRoute
    }
    '/_authenticated/rota/publications/$publicationId': {
      id: '/_authenticated/rota/publications/$publicationId'
      path: '/$publicationId'
      fullPath: '/rota/publications/$publicationId'
      preLoaderRoute: typeof AuthenticatedRotaPublicationsPublicationIdRouteImport
      parentRoute: typeof AuthenticatedRotaPublicationsRoute
    }
    '/_authenticated/rota/templates/': {
      id: '/_authenticated/rota/templates/'
      path: '/'
      fullPath: '/rota/templates/'
      preLoaderRoute: typeof AuthenticatedRotaTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRotaTemplatesRoute
    }
    '/_authenticated/rota/templates/$templateId': {
      id: '/_authenticated/rota/templates/$templateId'
      path: '/$templateId'
      fullPath: '/rota/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedRotaTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRotaTemplatesRoute
    }
    '/_authenticated/rota/publications/$publicationId/': {
      id: '/_authenticated/rota/publications/$publicationId/'
      path: '/'
      fullPath: '/rota/publications/$publicationId/'
      preLoaderRoute: typeof AuthenticatedRotaPublicationsPublicationIdIndexRouteImport
      parentRoute: typeof AuthenticatedRotaPublicationsPublicationIdRoute
    }
    '/_authenticated/rota/publications/$publicationId/assignments': {
      id: '/_authenticated/rota/publications/$publicationId/assignments'
      path: '/assignments'
      fullPath: '/rota/publications/$publicationId/assignments'
      preLoaderRoute: typeof AuthenticatedRotaPublicationsPublicationIdAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRotaPublicationsPublicationIdRoute
    }
    '/_authenticated/rota/publications/$publicationId/attendance': {
      id: '/_authenticated/rota/publications/$publicationId/attendance'
      path: '/attendance'
      fullPath: '/rota/publications/$publicationId/attendance'
      preLoaderRoute: typeof AuthenticatedRotaPublicationsPublicationIdAttendanceRouteImport
      parentRoute: typeof AuthenticatedRotaPublicationsPublicationIdRoute
    }
    '/_authenticated/rota/publications/$publicationId/availability': {
      id: '/_authenticated/rota/publications/$publicationId/availability'
      path: '/availability'
      fullPath: '/rota/publications/$publicationId/availability'
      preLoaderRoute: typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRotaPublicationsPublicationIdRoute
    }
    '/_authenticated/rota/publications/$publicationId/shift-changes': {
      id: '/_authenticated/rota/publications/$publicationId/shift-changes'
      path: '/shift-changes'
      fullPath: '/rota/publications/$publicationId/shift-changes'
      preLoaderRoute: typeof AuthenticatedRotaPublicationsPublicationIdShiftChangesRouteImport
      parentRoute: typeof AuthenticatedRotaPublicationsPublicationIdRoute
    }
    '/_authenticated/rota/publications/$publicationId/availability/': {
      id: '/_authenticated/rota/publications/$publicationId/availability/'
      path: '/'
      fullPath: '/rota/publications/$publicationId/availability/'
      preLoaderRoute: typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityIndexRouteImport
      parentRoute: typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityRoute
    }
    '/_authenticated/rota/publications/$publicationId/availability/$userId': {
      id: '/_authenticated/rota/publications/$publicationId/availability/$userId'
      path: '/$userId'
      fullPath: '/rota/publications/$publicationId/availability/$userId'
      preLoaderRoute: typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityUserIdRouteImport
      parentRoute: typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityRoute
    }
  }
}

interface AuthenticatedRotaLeavesRouteChildren {
  AuthenticatedRotaLeavesLeaveIdRoute: typeof AuthenticatedRotaLeavesLeaveIdRoute
  AuthenticatedRotaLeavesNewRoute: typeof AuthenticatedRotaLeavesNewRoute
  AuthenticatedRotaLeavesIndexRoute: typeof AuthenticatedRotaLeavesIndexRoute
}

const AuthenticatedRotaLeavesRouteChildren: AuthenticatedRotaLeavesRouteChildren =
  {
    AuthenticatedRotaLeavesLeaveIdRoute: AuthenticatedRotaLeavesLeaveIdRoute,
    AuthenticatedRotaLeavesNewRoute: AuthenticatedRotaLeavesNewRoute,
    AuthenticatedRotaLeavesIndexRoute: AuthenticatedRotaLeavesIndexRoute,
  }

const AuthenticatedRotaLeavesRouteWithChildren =
  AuthenticatedRotaLeavesRoute._addFileChildren(
    AuthenticatedRotaLeavesRouteChildren,
  )

interface AuthenticatedRotaPublicationsPublicationIdAvailabilityRouteChildren {
  AuthenticatedRotaPublicationsPublicationIdAvailabilityUserIdRoute: typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityUserIdRoute
  AuthenticatedRotaPublicationsPublicationIdAvailabilityIndexRoute: typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityIndexRoute
}

const AuthenticatedRotaPublicationsPublicationIdAvailabilityRouteChildren: AuthenticatedRotaPublicationsPublicationIdAvailabilityRouteChildren =
  {
    AuthenticatedRotaPublicationsPublicationIdAvailabilityUserIdRoute:
      AuthenticatedRotaPublicationsPublicationIdAvailabilityUserIdRoute,
    AuthenticatedRotaPublicationsPublicationIdAvailabilityIndexRoute:
      AuthenticatedRotaPublicationsPublicationIdAvailabilityIndexRoute,
  }

const AuthenticatedRotaPublicationsPublicationIdAvailabilityRouteWithChildren =
  AuthenticatedRotaPublicationsPublicationIdAvailabilityRoute._addFileChildren(
    AuthenticatedRotaPublicationsPublicationIdAvailabilityRouteChildren,
  )

interface AuthenticatedRotaPublicationsPublicationIdRouteChildren {
  AuthenticatedRotaPublicationsPublicationIdAssignmentsRoute: typeof AuthenticatedRotaPublicationsPublicationIdAssignmentsRoute
  AuthenticatedRotaPublicationsPublicationIdAttendanceRoute: typeof AuthenticatedRotaPublicationsPublicationIdAttendanceRoute
  AuthenticatedRotaPublicationsPublicationIdAvailabilityRoute: typeof AuthenticatedRotaPublicationsPublicationIdAvailabilityRouteWithChildren
  AuthenticatedRotaPublicationsPublicationIdShiftChangesRoute: typeof AuthenticatedRotaPublicationsPublicationIdShiftChangesRoute
  AuthenticatedRotaPublicationsPublicationIdIndexRoute: typeof AuthenticatedRotaPublicationsPublicationIdIndexRoute
}

const AuthenticatedRotaPublicationsPublicationIdRouteChildren: AuthenticatedRotaPublicationsPublicationIdRouteChildren =
  {
    AuthenticatedRotaPublicationsPublicationIdAssignmentsRoute:
      AuthenticatedRotaPublicationsPublicationIdAssignmentsRoute,
    AuthenticatedRotaPublicationsPublicationIdAttendanceRoute:
      AuthenticatedRotaPublicationsPublicationIdAttendanceRoute,
    AuthenticatedRotaPublicationsPublicationIdAvailabilityRoute:
      AuthenticatedRotaPublicationsPublicationIdAvailabilityRouteWithChildren,
    AuthenticatedRotaPublicationsPublicationIdShiftChangesRoute:
      AuthenticatedRotaPublicationsPublicationIdShiftChangesRoute,
    AuthenticatedRotaPublicationsPublicationIdIndexRoute:
      AuthenticatedRotaPublicationsPublicationIdIndexRoute,
  }

const AuthenticatedRotaPublicationsPublicationIdRouteWithChildren =
  AuthenticatedRotaPublicationsPublicationIdRoute._addFileChildren(
    AuthenticatedRotaPublicationsPublicationIdRouteChildren,
  )

interface AuthenticatedRotaPublicationsRouteChildren {
  AuthenticatedRotaPublicationsPublicationIdRoute: typeof AuthenticatedRotaPublicationsPublicationIdRouteWithChildren
  AuthenticatedRotaPublicationsIndexRoute: typeof AuthenticatedRotaPublicationsIndexRoute
}

const AuthenticatedRotaPublicationsRouteChildren: AuthenticatedRotaPublicationsRouteChildren =
  {
    AuthenticatedRotaPublicationsPublicationIdRoute:
      AuthenticatedRotaPublicationsPublicationIdRouteWithChildren,
    AuthenticatedRotaPublicationsIndexRoute:
      AuthenticatedRotaPublicationsIndexRoute,
  }

const AuthenticatedRotaPublicationsRouteWithChildren =
  AuthenticatedRotaPublicationsRoute._addFileChildren(
    AuthenticatedRotaPublicationsRouteChildren,
  )

interface AuthenticatedRotaTemplatesRouteChildren {
  AuthenticatedRotaTemplatesTemplateIdRoute: typeof AuthenticatedRotaTemplatesTemplateIdRoute
  AuthenticatedRotaTemplatesIndexRoute: typeof AuthenticatedRotaTemplatesIndexRoute
}

const AuthenticatedRotaTemplatesRouteChildren: AuthenticatedRotaTemplatesRouteChildren =
  {
    AuthenticatedRotaTemplatesTemplateIdRoute:
      AuthenticatedRotaTemplatesTemplateIdRoute,
    AuthenticatedRotaTemplatesIndexRoute: AuthenticatedRotaTemplatesIndexRoute,
  }

const AuthenticatedRotaTemplatesRouteWithChildren =
  AuthenticatedRotaTemplatesRoute._addFileChildren(
    AuthenticatedRotaTemplatesRouteChildren,
  )

interface AuthenticatedRotaRouteChildren {
  AuthenticatedRotaAttendanceRoute: typeof AuthenticatedRotaAttendanceRoute
  AuthenticatedRotaAvailabilityRoute: typeof AuthenticatedRotaAvailabilityRoute
  AuthenticatedRotaLeavesRoute: typeof AuthenticatedRotaLeavesRouteWithChildren
  AuthenticatedRotaPositionsRoute: typeof AuthenticatedRotaPositionsRoute
  AuthenticatedRotaPublicationsRoute: typeof AuthenticatedRotaPublicationsRouteWithChildren
  AuthenticatedRotaRequestsRoute: typeof AuthenticatedRotaRequestsRoute
  AuthenticatedRotaRosterRoute: typeof AuthenticatedRotaRosterRoute
  AuthenticatedRotaTemplatesRoute: typeof AuthenticatedRotaTemplatesRouteWithChildren
  AuthenticatedRotaIndexRoute: typeof AuthenticatedRotaIndexRoute
}

const AuthenticatedRotaRouteChildren: AuthenticatedRotaRouteChildren = {
  AuthenticatedRotaAttendanceRoute: AuthenticatedRotaAttendanceRoute,
  AuthenticatedRotaAvailabilityRoute: AuthenticatedRotaAvailabilityRoute,
  AuthenticatedRotaLeavesRoute: AuthenticatedRotaLeavesRouteWithChildren,
  AuthenticatedRotaPositionsRoute: AuthenticatedRotaPositionsRoute,
  AuthenticatedRotaPublicationsRoute:
    AuthenticatedRotaPublicationsRouteWithChildren,
  AuthenticatedRotaRequestsRoute: AuthenticatedRotaRequestsRoute,
  AuthenticatedRotaRosterRoute: AuthenticatedRotaRosterRoute,
  AuthenticatedRotaTemplatesRoute: AuthenticatedRotaTemplatesRouteWithChildren,
  AuthenticatedRotaIndexRoute: AuthenticatedRotaIndexRoute,
}

const AuthenticatedRotaRouteWithChildren =
  AuthenticatedRotaRoute._addFileChildren(AuthenticatedRotaRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedEmailTasksRoute: typeof AuthenticatedEmailTasksRoute
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedOnlineUsersRoute: typeof AuthenticatedOnlineUsersRoute
  AuthenticatedOperationLogsRoute: typeof AuthenticatedOperationLogsRoute
  AuthenticatedPersonalSettingsRoute: typeof AuthenticatedPersonalSettingsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedRotaRoute: typeof AuthenticatedRotaRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEmailTasksRoute: AuthenticatedEmailTasksRoute,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedOnlineUsersRoute: AuthenticatedOnlineUsersRoute,
  AuthenticatedOperationLogsRoute: AuthenticatedOperationLogsRoute,
  AuthenticatedPersonalSettingsRoute: AuthenticatedPersonalSettingsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedRotaRoute: AuthenticatedRotaRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
