services:
  postgres:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: