DROP VIEW IF EXISTS users;
DROP TRIGGER IF EXISTS template_slot_weekdays_no_overlap_trg ON template_slot_weekdays;
DROP FUNCTION IF EXISTS template_slot_weekday_no_overlap();
DROP INDEX IF EXISTS attendance_overtime_user_idx;
DROP INDEX IF EXISTS attendance_overtime_publication_occurrence_idx;
DROP TABLE IF EXISTS attendance_overtime_records;
DROP INDEX IF EXISTS attendance_records_user_idx;
DROP INDEX IF EXISTS attendance_records_publication_occurrence_idx;
DROP TABLE IF EXISTS attendance_records;
DROP INDEX IF EXISTS shift_change_requests_active_leave_occurrence_uidx;
DROP INDEX IF EXISTS shift_change_requests_leave_id_idx;
ALTER TABLE IF EXISTS shift_change_requests DROP CONSTRAINT IF EXISTS shift_change_requests_leave_id_fkey;
DROP TABLE IF EXISTS leaves;
DROP INDEX IF EXISTS shift_change_requests_counterpart_idx;
DROP INDEX IF EXISTS shift_change_requests_requester_idx;
DROP INDEX IF EXISTS shift_change_requests_publication_state_idx;
DROP TABLE IF EXISTS shift_change_requests;
DROP INDEX IF EXISTS assignment_overrides_user_id_idx;
DROP TABLE IF EXISTS assignment_overrides;
DROP TRIGGER IF EXISTS assignments_position_belongs_to_slot_trigger ON assignments;
DROP FUNCTION IF EXISTS assignments_position_belongs_to_slot();
DROP INDEX IF EXISTS assignments_publication_user_idx;
DROP INDEX IF EXISTS assignments_publication_slot_weekday_idx;
DROP TABLE IF EXISTS assignments;
DROP INDEX IF EXISTS availability_submissions_publication_slot_weekday_idx;
DROP INDEX IF EXISTS availability_submissions_publication_user_idx;
DROP TABLE IF EXISTS availability_submissions;
DROP INDEX IF EXISTS publications_single_non_ended_idx;
DROP TABLE IF EXISTS publications;
DROP INDEX IF EXISTS template_slot_positions_one_attendance_responsible_idx;
DROP TABLE IF EXISTS template_slot_positions;
DROP INDEX IF EXISTS template_slots_template_start_idx;
DROP TABLE IF EXISTS template_slot_weekdays;
DROP TABLE IF EXISTS template_slots;
DROP TABLE IF EXISTS templates;
DROP INDEX IF EXISTS user_positions_position_idx;
DROP TABLE IF EXISTS user_positions;
DROP TABLE IF EXISTS positions;
