// Code generated by backend/cmd/seed/scenarios/realistic_gen.py; DO NOT EDIT.

package scenarios

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	seedinternal "github.com/jonathanhu237/rota/backend/cmd/seed/internal"
	"github.com/jonathanhu237/rota/backend/internal/model"
)

const (
	realisticAssignmentSeed                = 20260428
	realisticExpectedAvailabilitySubmits   = 224
	realisticDomainFilteredSubmissionDrops = 140
)

const (
	realisticFrontLeadPosition = iota
	realisticFrontAssistantPosition
	realisticFieldLeadPosition
	realisticFieldAssistantPosition
)

type realisticEmployee struct {
	Slug     string
	Display  string
	Email    string
	Arch     archetype
	Weekdays [5][]int
}

type archetype int

const (
	FrontSenior archetype = iota
	FrontJunior
	FieldSenior
	FieldJunior
)

var realisticTimeSlots = [5]struct {
	Start string
	End   string
}{
	{Start: "09:00", End: "10:00"},
	{Start: "10:00", End: "12:00"},
	{Start: "13:30", End: "16:10"},
	{Start: "16:10", End: "18:00"},
	{Start: "19:00", End: "21:00"},
}

var realisticEmployees = [42]realisticEmployee{
	{
		Slug:    "employee01",
		Display: "员工 1",
		Email:   "employee01@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{1, 2, 4, 5, 6},
			[]int{1, 2, 4, 5, 6},
			[]int{1, 2, 4},
			[]int{1, 2, 3, 4, 5},
			[]int{1, 2, 3, 4, 5, 6, 7},
		},
	},
	{
		Slug:    "employee02",
		Display: "员工 2",
		Email:   "employee02@example.com",
		Arch:    FrontSenior,
		Weekdays: [5][]int{
			[]int{2, 4},
			[]int{2, 4},
			[]int{},
			[]int{},
			[]int{1, 2, 4},
		},
	},
	{
		Slug:    "employee03",
		Display: "员工 3",
		Email:   "employee03@example.com",
		Arch:    FieldJunior,
		Weekdays: [5][]int{
			[]int{},
			[]int{2},
			[]int{5},
			[]int{4, 5},
			[]int{3, 7},
		},
	},
	{
		Slug:    "employee04",
		Display: "员工 4",
		Email:   "employee04@example.com",
		Arch:    FrontSenior,
		Weekdays: [5][]int{
			[]int{},
			[]int{},
			[]int{3, 5},
			[]int{3, 5},
			[]int{2, 3, 4},
		},
	},
	{
		Slug:    "employee05",
		Display: "员工 5",
		Email:   "employee05@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{3, 6},
			[]int{1, 3, 6},
			[]int{1, 3},
			[]int{1, 3},
			[]int{},
		},
	},
	{
		Slug:    "employee06",
		Display: "员工 6",
		Email:   "employee06@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{},
			[]int{},
			[]int{1, 3},
			[]int{2, 4},
			[]int{},
		},
	},
	{
		Slug:    "employee07",
		Display: "员工 7",
		Email:   "employee07@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{3},
			[]int{3},
			[]int{},
			[]int{},
			[]int{5},
		},
	},
	{
		Slug:    "employee08",
		Display: "员工 8",
		Email:   "employee08@example.com",
		Arch:    FrontSenior,
		Weekdays: [5][]int{
			[]int{},
			[]int{6},
			[]int{},
			[]int{},
			[]int{4, 5},
		},
	},
	{
		Slug:    "employee09",
		Display: "员工 9",
		Email:   "employee09@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{6},
			[]int{6},
			[]int{2},
			[]int{2, 4},
			[]int{2},
		},
	},
	{
		Slug:    "employee10",
		Display: "员工 10",
		Email:   "employee10@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{},
			[]int{},
			[]int{},
			[]int{},
			[]int{2, 3, 4},
		},
	},
	{
		Slug:    "employee11",
		Display: "员工 11",
		Email:   "employee11@example.com",
		Arch:    FrontSenior,
		Weekdays: [5][]int{
			[]int{},
			[]int{1, 2, 3, 4, 5, 6},
			[]int{},
			[]int{2, 5},
			[]int{1, 2, 4, 5, 6, 7},
		},
	},
	{
		Slug:    "employee12",
		Display: "员工 12",
		Email:   "employee12@example.com",
		Arch:    FrontSenior,
		Weekdays: [5][]int{
			[]int{3},
			[]int{5},
			[]int{4},
			[]int{4},
			[]int{2, 4},
		},
	},
	{
		Slug:    "employee13",
		Display: "员工 13",
		Email:   "employee13@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{},
			[]int{},
			[]int{},
			[]int{},
			[]int{2, 3, 4},
		},
	},
	{
		Slug:    "employee14",
		Display: "员工 14",
		Email:   "employee14@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{},
			[]int{},
			[]int{},
			[]int{2, 5},
			[]int{2, 4, 5},
		},
	},
	{
		Slug:    "employee15",
		Display: "员工 15",
		Email:   "employee15@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{},
			[]int{},
			[]int{2, 4},
			[]int{2, 4},
			[]int{3},
		},
	},
	{
		Slug:    "employee16",
		Display: "员工 16",
		Email:   "employee16@example.com",
		Arch:    FrontSenior,
		Weekdays: [5][]int{
			[]int{},
			[]int{},
			[]int{2, 4},
			[]int{2, 4},
			[]int{},
		},
	},
	{
		Slug:    "employee17",
		Display: "员工 17",
		Email:   "employee17@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{},
			[]int{},
			[]int{2},
			[]int{2, 4},
			[]int{2},
		},
	},
	{
		Slug:    "employee18",
		Display: "员工 18",
		Email:   "employee18@example.com",
		Arch:    FieldJunior,
		Weekdays: [5][]int{
			[]int{5, 6},
			[]int{5, 6},
			[]int{2, 5},
			[]int{3, 5},
			[]int{},
		},
	},
	{
		Slug:    "employee19",
		Display: "员工 19",
		Email:   "employee19@example.com",
		Arch:    FieldSenior,
		Weekdays: [5][]int{
			[]int{},
			[]int{},
			[]int{},
			[]int{2},
			[]int{2},
		},
	},
	{
		Slug:    "employee20",
		Display: "员工 20",
		Email:   "employee20@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{2},
			[]int{5},
			[]int{3, 5},
			[]int{5},
			[]int{2, 3, 5, 6, 7},
		},
	},
	{
		Slug:    "employee21",
		Display: "员工 21",
		Email:   "employee21@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{2, 3, 4, 5},
			[]int{2, 3, 4, 5},
			[]int{1, 2, 3, 4, 5},
			[]int{1, 2, 3, 4, 5},
			[]int{},
		},
	},
	{
		Slug:    "employee22",
		Display: "员工 22",
		Email:   "employee22@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{1, 2, 3, 4, 5, 6},
			[]int{1, 2, 3, 4, 5, 6},
			[]int{},
			[]int{},
			[]int{},
		},
	},
	{
		Slug:    "employee23",
		Display: "员工 23",
		Email:   "employee23@example.com",
		Arch:    FieldSenior,
		Weekdays: [5][]int{
			[]int{2, 5, 6},
			[]int{5, 6},
			[]int{},
			[]int{2},
			[]int{1, 2, 4, 5},
		},
	},
	{
		Slug:    "employee24",
		Display: "员工 24",
		Email:   "employee24@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{2},
			[]int{2},
			[]int{},
			[]int{3, 5},
			[]int{2, 3, 5},
		},
	},
	{
		Slug:    "employee25",
		Display: "员工 25",
		Email:   "employee25@example.com",
		Arch:    FieldSenior,
		Weekdays: [5][]int{
			[]int{},
			[]int{1, 3},
			[]int{1, 2, 3},
			[]int{},
			[]int{},
		},
	},
	{
		Slug:    "employee26",
		Display: "员工 26",
		Email:   "employee26@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{1, 2, 4, 5, 6},
			[]int{1, 2, 4, 5, 6},
			[]int{1, 2, 3, 4, 5},
			[]int{1, 2, 3, 4, 5},
			[]int{1, 2, 3, 4, 5, 6, 7},
		},
	},
	{
		Slug:    "employee27",
		Display: "员工 27",
		Email:   "employee27@example.com",
		Arch:    FieldSenior,
		Weekdays: [5][]int{
			[]int{1, 2, 3, 4, 5, 6},
			[]int{1, 2, 4, 6},
			[]int{},
			[]int{1, 2},
			[]int{1, 2, 3, 4, 6, 7},
		},
	},
	{
		Slug:    "employee28",
		Display: "员工 28",
		Email:   "employee28@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{},
			[]int{},
			[]int{1, 2, 3, 4},
			[]int{1, 2, 3, 4, 5},
			[]int{2, 4, 5},
		},
	},
	{
		Slug:    "employee29",
		Display: "员工 29",
		Email:   "employee29@example.com",
		Arch:    FieldJunior,
		Weekdays: [5][]int{
			[]int{},
			[]int{2},
			[]int{},
			[]int{2, 3, 5},
			[]int{},
		},
	},
	{
		Slug:    "employee30",
		Display: "员工 30",
		Email:   "employee30@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{2, 5},
			[]int{2, 6},
			[]int{},
			[]int{3, 4},
			[]int{2, 3, 5, 6, 7},
		},
	},
	{
		Slug:    "employee31",
		Display: "员工 31",
		Email:   "employee31@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{5, 6},
			[]int{5, 6},
			[]int{},
			[]int{},
			[]int{},
		},
	},
	{
		Slug:    "employee32",
		Display: "员工 32",
		Email:   "employee32@example.com",
		Arch:    FrontSenior,
		Weekdays: [5][]int{
			[]int{},
			[]int{},
			[]int{2, 3, 4},
			[]int{},
			[]int{2, 3, 4},
		},
	},
	{
		Slug:    "employee33",
		Display: "员工 33",
		Email:   "employee33@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{3, 4, 6},
			[]int{3, 4, 6},
			[]int{2, 4, 5},
			[]int{2, 4, 5},
			[]int{2, 3, 4, 5},
		},
	},
	{
		Slug:    "employee34",
		Display: "员工 34",
		Email:   "employee34@example.com",
		Arch:    FrontSenior,
		Weekdays: [5][]int{
			[]int{1, 2, 3, 5, 6},
			[]int{6},
			[]int{},
			[]int{1, 2, 3, 4, 5},
			[]int{1, 2, 3, 4, 5, 6, 7},
		},
	},
	{
		Slug:    "employee35",
		Display: "员工 35",
		Email:   "employee35@example.com",
		Arch:    FieldJunior,
		Weekdays: [5][]int{
			[]int{1, 2, 3, 4, 5, 6},
			[]int{},
			[]int{},
			[]int{},
			[]int{6},
		},
	},
	{
		Slug:    "employee36",
		Display: "员工 36",
		Email:   "employee36@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{2, 6},
			[]int{2, 6},
			[]int{4, 5},
			[]int{3, 4},
			[]int{1, 2, 5, 6, 7},
		},
	},
	{
		Slug:    "employee37",
		Display: "员工 37",
		Email:   "employee37@example.com",
		Arch:    FieldJunior,
		Weekdays: [5][]int{
			[]int{3},
			[]int{3},
			[]int{2},
			[]int{2},
			[]int{},
		},
	},
	{
		Slug:    "employee38",
		Display: "员工 38",
		Email:   "employee38@example.com",
		Arch:    FrontSenior,
		Weekdays: [5][]int{
			[]int{1, 2, 3, 5},
			[]int{2, 3, 5, 6},
			[]int{1, 2, 3, 5},
			[]int{1, 2, 5},
			[]int{5},
		},
	},
	{
		Slug:    "employee39",
		Display: "员工 39",
		Email:   "employee39@example.com",
		Arch:    FrontSenior,
		Weekdays: [5][]int{
			[]int{2},
			[]int{2},
			[]int{},
			[]int{5},
			[]int{1, 2},
		},
	},
	{
		Slug:    "employee40",
		Display: "员工 40",
		Email:   "employee40@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{2},
			[]int{2},
			[]int{},
			[]int{},
			[]int{2},
		},
	},
	{
		Slug:    "employee41",
		Display: "员工 41",
		Email:   "employee41@example.com",
		Arch:    FrontJunior,
		Weekdays: [5][]int{
			[]int{},
			[]int{3, 4},
			[]int{2},
			[]int{4},
			[]int{2, 3, 4, 5, 6, 7},
		},
	},
	{
		Slug:    "employee42",
		Display: "员工 42",
		Email:   "employee42@example.com",
		Arch:    FieldJunior,
		Weekdays: [5][]int{
			[]int{6},
			[]int{6},
			[]int{},
			[]int{},
			[]int{6, 7},
		},
	},
}

func RunRealistic(ctx context.Context, tx *sql.Tx, opts Options) error {
	if _, _, err := insertUsers(ctx, tx, opts, 0); err != nil {
		return err
	}

	positionIDs, err := insertRealisticPositions(ctx, tx, opts.Now)
	if err != nil {
		return err
	}

	userIDs, err := insertRealisticEmployees(ctx, tx)
	if err != nil {
		return err
	}
	if err := insertRealisticUserPositions(ctx, tx, userIDs, positionIDs); err != nil {
		return err
	}

	templateID, err := insertTemplate(ctx, tx, "Realistic Rota", true, opts.Now)
	if err != nil {
		return err
	}
	slotIDs, err := insertRealisticSlots(ctx, tx, templateID, positionIDs, opts.Now)
	if err != nil {
		return err
	}

	activeFrom := opts.Now.Add(7 * 24 * time.Hour)
	publicationID, err := insertPublication(
		ctx,
		tx,
		templateID,
		"Realistic Rota Week",
		model.PublicationStateDraft,
		opts.Now.Add(-14*24*time.Hour),
		opts.Now.Add(-7*24*time.Hour),
		activeFrom,
		activeFrom.Add(7*24*time.Hour),
		nil,
		opts.Now,
	)
	if err != nil {
		return err
	}

	return insertRealisticAvailabilitySubmissions(ctx, tx, publicationID, userIDs, slotIDs, opts.Now)
}

func insertRealisticPositions(ctx context.Context, tx *sql.Tx, now time.Time) ([4]int64, error) {
	definitions := [4]struct {
		Name        string
		Description string
	}{
		{Name: "前台负责人", Description: "Realistic front desk lead"},
		{Name: "前台助理", Description: "Realistic front desk assistant"},
		{Name: "外勤负责人", Description: "Realistic field lead"},
		{Name: "外勤助理", Description: "Realistic field assistant"},
	}

	var ids [4]int64
	for index, definition := range definitions {
		if err := tx.QueryRowContext(
			ctx,
			`
				INSERT INTO positions (name, description, created_at, updated_at)
				VALUES ($1, $2, $3, $3)
				RETURNING id;
			`,
			definition.Name,
			definition.Description,
			now,
		).Scan(&ids[index]); err != nil {
			return ids, fmt.Errorf("insert realistic position %q: %w", definition.Name, err)
		}
	}
	return ids, nil
}

func insertRealisticEmployees(ctx context.Context, tx *sql.Tx) ([42]int64, error) {
	var ids [42]int64
	for index, employee := range realisticEmployees {
		id, err := seedinternal.InsertUser(ctx, tx, employee.Email, employee.Display, SeedPassword, false)
		if err != nil {
			return ids, fmt.Errorf("insert realistic employee %s: %w", employee.Slug, err)
		}
		ids[index] = id
	}
	return ids, nil
}

func insertRealisticUserPositions(ctx context.Context, tx *sql.Tx, userIDs [42]int64, positionIDs [4]int64) error {
	for employeeIndex, employee := range realisticEmployees {
		indexes, err := employee.Arch.positionIndexes()
		if err != nil {
			return fmt.Errorf("resolve positions for %s: %w", employee.Slug, err)
		}
		for _, positionIndex := range indexes {
			if _, err := tx.ExecContext(
				ctx,
				`INSERT INTO user_positions (user_id, position_id) VALUES ($1, $2);`,
				userIDs[employeeIndex],
				positionIDs[positionIndex],
			); err != nil {
				return fmt.Errorf("qualify realistic employee %s for position index %d: %w", employee.Slug, positionIndex, err)
			}
		}
	}
	return nil
}

func insertRealisticSlots(ctx context.Context, tx *sql.Tx, templateID int64, positionIDs [4]int64, now time.Time) ([5][8]int64, error) {
	var slotIDs [5][8]int64
	for timeIndex, slot := range realisticTimeSlots {
		var slotID int64
		if err := tx.QueryRowContext(
			ctx,
			`
				INSERT INTO template_slots (template_id, start_time, end_time, created_at, updated_at)
				VALUES ($1, $2, $3, $4, $4)
				RETURNING id;
			`,
			templateID,
			slot.Start,
			slot.End,
			now,
		).Scan(&slotID); err != nil {
			return slotIDs, fmt.Errorf("insert realistic slot %s-%s: %w", slot.Start, slot.End, err)
		}

		for weekday := 1; weekday <= 7; weekday++ {
			if _, err := tx.ExecContext(
				ctx,
				`INSERT INTO template_slot_weekdays (slot_id, weekday) VALUES ($1, $2);`,
				slotID,
				weekday,
			); err != nil {
				return slotIDs, fmt.Errorf("insert realistic slot-weekday slot=%d weekday=%d: %w", slotID, weekday, err)
			}
			slotIDs[timeIndex][weekday] = slotID
		}

		positions := realisticSlotPositions(timeIndex)
		for _, position := range positions {
			if _, err := tx.ExecContext(
				ctx,
				`
					INSERT INTO template_slot_positions (slot_id, position_id, required_headcount, created_at, updated_at)
					VALUES ($1, $2, $3, $4, $4);
				`,
				slotID,
				positionIDs[position.PositionIndex],
				position.RequiredHeadcount,
				now,
			); err != nil {
				return slotIDs, fmt.Errorf("insert realistic slot-position slot=%d position=%d: %w", slotID, position.PositionIndex, err)
			}
		}
	}
	return slotIDs, nil
}

func realisticSlotPositions(timeIndex int) []positionHeadcount {
	if timeIndex < 4 {
		return []positionHeadcount{
			{PositionIndex: realisticFrontLeadPosition, RequiredHeadcount: 1},
			{PositionIndex: realisticFrontAssistantPosition, RequiredHeadcount: 2},
		}
	}
	return []positionHeadcount{
		{PositionIndex: realisticFieldLeadPosition, RequiredHeadcount: 1},
		{PositionIndex: realisticFieldAssistantPosition, RequiredHeadcount: 1},
	}
}

func insertRealisticAvailabilitySubmissions(
	ctx context.Context,
	tx *sql.Tx,
	publicationID int64,
	userIDs [42]int64,
	slotIDs [5][8]int64,
	now time.Time,
) error {
	inserted := 0
	for employeeIndex, employee := range realisticEmployees {
		for timeIndex, weekdays := range employee.Weekdays {
			if !employee.Arch.matchesTimeSlot(timeIndex) {
				continue
			}
			for _, weekday := range weekdays {
				if weekday < 1 || weekday > 7 {
					return fmt.Errorf("realistic employee %s has invalid weekday %d", employee.Slug, weekday)
				}
				slotID := slotIDs[timeIndex][weekday]
				if slotID == 0 {
					return fmt.Errorf("missing realistic slot id for time index %d weekday %d", timeIndex, weekday)
				}
				if _, err := tx.ExecContext(
					ctx,
					`
						INSERT INTO availability_submissions (
							publication_id,
							user_id,
							slot_id,
							weekday,
							created_at
						)
						VALUES ($1, $2, $3, $4, $5);
					`,
					publicationID,
					userIDs[employeeIndex],
					slotID,
					weekday,
					now,
				); err != nil {
					return fmt.Errorf("insert realistic availability employee=%s slot=%d weekday=%d: %w", employee.Slug, slotID, weekday, err)
				}
				inserted++
			}
		}
	}
	if inserted != realisticExpectedAvailabilitySubmits {
		return fmt.Errorf("realistic availability count mismatch: inserted %d, expected %d", inserted, realisticExpectedAvailabilitySubmits)
	}
	return nil
}

func (arch archetype) positionIndexes() ([]int, error) {
	switch arch {
	case FrontSenior:
		return []int{realisticFrontLeadPosition, realisticFrontAssistantPosition}, nil
	case FrontJunior:
		return []int{realisticFrontAssistantPosition}, nil
	case FieldSenior:
		return []int{realisticFieldLeadPosition, realisticFieldAssistantPosition}, nil
	case FieldJunior:
		return []int{realisticFieldAssistantPosition}, nil
	default:
		return nil, fmt.Errorf("unknown archetype %d", arch)
	}
}

func (arch archetype) matchesTimeSlot(timeIndex int) bool {
	switch arch {
	case FrontSenior, FrontJunior:
		return timeIndex < 4
	case FieldSenior, FieldJunior:
		return timeIndex == 4
	default:
		return false
	}
}
