/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupPasswordRouteImport } from './routes/setup-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as AuthenticatedAvailabilityRouteImport } from './routes/_authenticated/availability'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates/index'
import { Route as AuthenticatedPublicationsIndexRouteImport } from './routes/_authenticated/publications/index'
import { Route as AuthenticatedPositionsIndexRouteImport } from './routes/_authenticated/positions/index'
import { Route as AuthenticatedTemplatesTemplateIdRouteImport } from './routes/_authenticated/templates/$templateId'
import { Route as AuthenticatedPublicationsPublicationIdRouteImport } from './routes/_authenticated/publications/$publicationId'
import { Route as AuthenticatedPublicationsPublicationIdAssignmentsRouteImport } from './routes/_authenticated/publications/$publicationId/assignments'

const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAvailabilityRoute =
  AuthenticatedAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPublicationsIndexRoute =
  AuthenticatedPublicationsIndexRouteImport.update({
    id: '/publications/',
    path: '/publications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPositionsIndexRoute =
  AuthenticatedPositionsIndexRouteImport.update({
    id: '/positions/',
    path: '/positions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTemplatesTemplateIdRoute =
  AuthenticatedTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPublicationsPublicationIdRoute =
  AuthenticatedPublicationsPublicationIdRouteImport.update({
    id: '/publications/$publicationId',
    path: '/publications/$publicationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPublicationsPublicationIdAssignmentsRoute =
  AuthenticatedPublicationsPublicationIdAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedPublicationsPublicationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup-password': typeof SetupPasswordRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/publications/$publicationId': typeof AuthenticatedPublicationsPublicationIdRouteWithChildren
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/positions/': typeof AuthenticatedPositionsIndexRoute
  '/publications/': typeof AuthenticatedPublicationsIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/publications/$publicationId/assignments': typeof AuthenticatedPublicationsPublicationIdAssignmentsRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup-password': typeof SetupPasswordRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/': typeof AuthenticatedIndexRoute
  '/publications/$publicationId': typeof AuthenticatedPublicationsPublicationIdRouteWithChildren
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/positions': typeof AuthenticatedPositionsIndexRoute
  '/publications': typeof AuthenticatedPublicationsIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/publications/$publicationId/assignments': typeof AuthenticatedPublicationsPublicationIdAssignmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup-password': typeof SetupPasswordRoute
  '/_authenticated/availability': typeof AuthenticatedAvailabilityRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/publications/$publicationId': typeof AuthenticatedPublicationsPublicationIdRouteWithChildren
  '/_authenticated/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/_authenticated/positions/': typeof AuthenticatedPositionsIndexRoute
  '/_authenticated/publications/': typeof AuthenticatedPublicationsIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/publications/$publicationId/assignments': typeof AuthenticatedPublicationsPublicationIdAssignmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/setup-password'
    | '/availability'
    | '/roster'
    | '/publications/$publicationId'
    | '/templates/$templateId'
    | '/positions/'
    | '/publications/'
    | '/templates/'
    | '/users/'
    | '/publications/$publicationId/assignments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/setup-password'
    | '/availability'
    | '/roster'
    | '/'
    | '/publications/$publicationId'
    | '/templates/$templateId'
    | '/positions'
    | '/publications'
    | '/templates'
    | '/users'
    | '/publications/$publicationId/assignments'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/setup-password'
    | '/_authenticated/availability'
    | '/_authenticated/roster'
    | '/_authenticated/'
    | '/_authenticated/publications/$publicationId'
    | '/_authenticated/templates/$templateId'
    | '/_authenticated/positions/'
    | '/_authenticated/publications/'
    | '/_authenticated/templates/'
    | '/_authenticated/users/'
    | '/_authenticated/publications/$publicationId/assignments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SetupPasswordRoute: typeof SetupPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-password': {
      id: '/setup-password'
      path: '/setup-password'
      fullPath: '/setup-password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/availability': {
      id: '/_authenticated/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AuthenticatedAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/publications/': {
      id: '/_authenticated/publications/'
      path: '/publications'
      fullPath: '/publications/'
      preLoaderRoute: typeof AuthenticatedPublicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/positions/': {
      id: '/_authenticated/positions/'
      path: '/positions'
      fullPath: '/positions/'
      preLoaderRoute: typeof AuthenticatedPositionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/$templateId': {
      id: '/_authenticated/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/publications/$publicationId': {
      id: '/_authenticated/publications/$publicationId'
      path: '/publications/$publicationId'
      fullPath: '/publications/$publicationId'
      preLoaderRoute: typeof AuthenticatedPublicationsPublicationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/publications/$publicationId/assignments': {
      id: '/_authenticated/publications/$publicationId/assignments'
      path: '/assignments'
      fullPath: '/publications/$publicationId/assignments'
      preLoaderRoute: typeof AuthenticatedPublicationsPublicationIdAssignmentsRouteImport
      parentRoute: typeof AuthenticatedPublicationsPublicationIdRoute
    }
  }
}

interface AuthenticatedPublicationsPublicationIdRouteChildren {
  AuthenticatedPublicationsPublicationIdAssignmentsRoute: typeof AuthenticatedPublicationsPublicationIdAssignmentsRoute
}

const AuthenticatedPublicationsPublicationIdRouteChildren: AuthenticatedPublicationsPublicationIdRouteChildren =
  {
    AuthenticatedPublicationsPublicationIdAssignmentsRoute:
      AuthenticatedPublicationsPublicationIdAssignmentsRoute,
  }

const AuthenticatedPublicationsPublicationIdRouteWithChildren =
  AuthenticatedPublicationsPublicationIdRoute._addFileChildren(
    AuthenticatedPublicationsPublicationIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAvailabilityRoute: typeof AuthenticatedAvailabilityRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPublicationsPublicationIdRoute: typeof AuthenticatedPublicationsPublicationIdRouteWithChildren
  AuthenticatedTemplatesTemplateIdRoute: typeof AuthenticatedTemplatesTemplateIdRoute
  AuthenticatedPositionsIndexRoute: typeof AuthenticatedPositionsIndexRoute
  AuthenticatedPublicationsIndexRoute: typeof AuthenticatedPublicationsIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAvailabilityRoute: AuthenticatedAvailabilityRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPublicationsPublicationIdRoute:
    AuthenticatedPublicationsPublicationIdRouteWithChildren,
  AuthenticatedTemplatesTemplateIdRoute: AuthenticatedTemplatesTemplateIdRoute,
  AuthenticatedPositionsIndexRoute: AuthenticatedPositionsIndexRoute,
  AuthenticatedPublicationsIndexRoute: AuthenticatedPublicationsIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SetupPasswordRoute: SetupPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
